In [2]:
import json
import numpy as np
import pandas as pd
import geopandas as gpd
import sys
import os
import imageio
import csv
import matplotlib.pyplot as plt
from PIL import Image
import os
from collections import defaultdict

# Radiant Earth Foundation Field Boundaries

## Kenya

In [51]:
base_dir = '../../mlhub-tutorials/data/ref_african_crops_kenya_01_labels/'
label_dirs = [x for x in os.listdir(base_dir) if 'ref' in x]

dataframes_list = []
for label_dir in label_dirs:
    label_path = os.path.join(base_dir, label_dir, 'labels.geojson')
    print(gpd.read_file(label_path).shape)
    dataframes_list.append(gpd.read_file(label_path))
labels = gpd.GeoDataFrame(pd.concat(dataframes_list, ignore_index=True), crs=dataframes_list[0].crs)
labels.to_file("../data/parcels/radiant/ref_african_crops_kenya_01_labels.shp")
print(labels.shape)

(67, 21)
(159, 21)
(93, 21)
(319, 21)

In [26]:
labels.head()

,Field ID,Latitude,Longitude,Accuracy,Survey Date,Water Resource,Planting Date,PlantingDate Method,Estimated Harvest Date,Crop1,...,Crop3,Crop4,Crop5,Crop Density,Variety,CMD Rating,CBSD Rating,CGM Rating,Disease Rating,geometry
0,4.15,0.565611,34.29758,4.288,2019-05-14,rainfed,2019-01-31,Recorded,2019-09-30,Millet,...,,,,95,Null,Null,Null,Null,Null,"POLYGON ((644386.114 62530.949, 644350.540 625..."
1,4.14,0.565387,34.29778,4.288,2019-05-14,rainfed,2019-04-01,Estimated,2020-02-01,Cassava,...,,,,50,Null,Null,Null,Null,Null,"POLYGON ((644384.771 62522.783, 644405.882 625..."
2,4.11,0.564693,34.29752,4.288,2019-05-14,rainfed,2019-03-01,Estimated,2019-12-01,Maize,...,,,,75,Null,Null,Null,Null,Null,"POLYGON ((644406.947 62434.880, 644338.999 624..."
3,4.15.1,0.565702,34.29755,4.288,2019-05-14,rainfed,2019-01-01,Estimated,2020-01-01,Groundnut,...,,,,50,Null,Null,Null,Null,Null,"POLYGON ((644392.094 62529.911, 644384.615 625..."
4,4.10.1,0.564271,34.29732,4.288,2019-05-14,rainfed,2019-04-01,Estimated,2020-02-01,Cassava,...,,,,40,Null,2,4,8,Null,"POLYGON ((644360.314 62383.237, 644356.395 624..."

## Tanzania

In [29]:
base_dir = '../../mlhub-tutorials/data/ref_african_crops_tanzania_01_labels/'
label_dirs = [x for x in os.listdir(base_dir) if 'ref' in x]

dataframes_list = []
for label_dir in label_dirs:
    label_path = os.path.join(base_dir, label_dir, 'labels.geojson')
    dataframes_list.append(gpd.read_file(label_path))
labels = gpd.GeoDataFrame(pd.concat(dataframes_list, ignore_index=True), crs=dataframes_list[0].crs)
labels.to_file("../data/parcels/radiant/ref_african_crops_tanzania_01_labels.shp")
print(labels.shape)

(392, 7)

In [30]:
labels.head()

,Village,Region,Plot Area (acre),Planting Date,Estimated Harvest Date,Crop,geometry
0,Osilale-Nadonjuki,Manyara,100,2018-03-23,2018-07-23,Bush Bean,"POLYGON ((909321.895 9564384.304, 909472.077 9..."
1,Monduli,Arusha,50,2018-01-23,2018-08-23,Yellow Maize,"POLYGON ((908151.312 9559612.952, 908309.945 9..."
2,Upper Kitete,Arusha,9,2018-03-26,2018-07-26,Bush Bean,"POLYGON ((787595.863 9631415.669, 787646.610 9..."
3,Arusha (municipal),Arusha,13,2018-03-31,2018-07-31,Bush Bean,"POLYGON ((961277.536 9516916.203, 961360.163 9..."
4,Langai,Manyara,30,2018-04-06,2018-08-06,Bush Bean,"POLYGON ((964901.679 9519678.994, 965060.337 9..."

## Uganda

In [31]:
base_dir = '../../mlhub-tutorials/data/ref_african_crops_uganda_01_labels/'
label_dirs = [x for x in os.listdir(base_dir) if 'ref' in x]

dataframes_list = []
for label_dir in label_dirs:
    label_path = os.path.join(base_dir, label_dir, 'labels.geojson')
    dataframes_list.append(gpd.read_file(label_path))
labels = gpd.GeoDataFrame(pd.concat(dataframes_list, ignore_index=True), crs=dataframes_list[0].crs)
labels.to_file("../data/parcels/radiant/ref_african_crops_uganda_01_labels.shp")
print(labels.shape)

(234, 93)

In [32]:
labels.head()

,Village,Subcounty,District,surveyorid,quadrant,crop1,variety1,m_plant1,m_cob1,m_disease1,...,s_ear8,s_disease8,Moisture,Grain_W_g,Stem_W_g,Yield_KgHa,HI,Estimated Planting Date,Estimated Harvest Date,geometry
0,Lomoruchubai,NAPAK TOWN COUNCIL,NAPAK,314,5,maize,indigenous,6,6,0,...,None,None,0.110,195.0,407.5,866.7,0.324,2017-01-01,2017-12-31,"POLYGON ((650595.080 238410.484, 650595.708 23..."
1,Lokanyurunyurwi,NAPAK TOWN COUNCIL,NAPAK,316,7,maize,indigenous,7,7,1,...,None,None,0.111,212.1,810.0,942.9,0.208,2017-01-01,2017-12-31,"POLYGON ((649719.349 238404.995, 649689.055 23..."
2,Kadilakeng,RUPA,MOROTO,314,8,sorghum,improved,None,None,None,...,3,1,0.036,36.3,1532.5,161.1,0.023,2017-01-01,2017-12-31,"POLYGON ((683443.982 286152.041, 683360.864 28..."
3,Kanakol,RUPA,MOROTO,314,8,sorghum,improved,None,None,None,...,20,1,0.036,37.1,965.0,165.1,0.037,2017-01-01,2017-12-31,"POLYGON ((679853.175 286045.266, 679854.073 28..."
4,Longaroi,LOTOME,NAPAK,315,8,sorghum,indigenous,None,None,None,...,20,1,0.040,120.6,875.0,536.1,0.121,2017-01-01,2017-12-31,"POLYGON ((667425.842 264182.796, 667386.701 26..."

## Benin

In [42]:
label_path = '../../mlhub-tutorials/data/ts_cashew_benin_labels/_common/labels.geojson'
labels = gpd.read_file(label_path)
labels.to_file("../data/parcels/radiant/ts_cashew_benin_labels.shp")
print(labels.shape)

(1851, 6)

In [41]:
labels.head()

,OBJECTID,class,Shape_Leng,Shape_Area,class_name,geometry
0,1,1,367629.523311,1.699754e+07,Well-managed planatation,"POLYGON ((447131.215 1001286.636, 447166.272 1..."
1,1,1,367629.523311,1.699754e+07,Well-managed planatation,"POLYGON ((444422.669 1001301.178, 444399.641 1..."
2,1,1,367629.523311,1.699754e+07,Well-managed planatation,"POLYGON ((444533.265 1001236.884, 444530.617 1..."
3,1,1,367629.523311,1.699754e+07,Well-managed planatation,"POLYGON ((443708.293 1001345.628, 443701.144 1..."
4,1,1,367629.523311,1.699754e+07,Well-managed planatation,"POLYGON ((441946.507 1001392.384, 441975.082 1..."

## Central Asia

In [54]:
label_path = '../../mlhub-tutorials/data/idiv_asia_crop_type_labels/_common/labels.geojson'
labels = gpd.read_file(label_path)
labels.to_file("../data/parcels/radiant/idiv_asia_crop_type_labels.shp")
print(labels.shape)

(8435, 10)

In [45]:
labels.head()

,sampler,country,region,date,year,season,crop_1,crop_2,ndvi,geometry
0,SIC-ICWC,Uzbekistan,Fergana,2011-06-14,2011,summer,cotton,N/A,"{'2011-01-01': '0.111307774141834', '2011-01-1...","MULTIPOLYGON (((71.53066 40.49702, 71.53303 40..."
1,SIC-ICWC,Uzbekistan,Fergana,2011-06-14,2011,summer,cotton,N/A,"{'2011-01-01': '0.126650983565732', '2011-01-1...","MULTIPOLYGON (((71.54027 40.49276, 71.54520 40..."
2,SIC-ICWC,Uzbekistan,Fergana,2011-06-14,2011,summer,cotton,N/A,"{'2011-01-01': '0.147239392811014', '2011-01-1...","MULTIPOLYGON (((71.54803 40.49244, 71.55068 40..."
3,SIC-ICWC,Uzbekistan,Fergana,2011-06-14,2011,double,wheat,other,"{'2011-01-01': '0.15613025771454', '2011-01-17...","MULTIPOLYGON (((71.54542 40.49040, 71.54849 40..."
4,SIC-ICWC,Uzbekistan,Fergana,2011-06-14,2011,summer,cotton,N/A,"{'2011-01-01': '0.108602782894695', '2011-01-1...","MULTIPOLYGON (((71.55015 40.48437, 71.55099 40..."

In [48]:
labels.shape

(8435, 10)

In [56]:
labels.groupby(['country', 'year']).size()

country     year
Tajikistan  2016     189
Uzbekistan  2008      26
            2011     213
            2015    1299
            2016    3880
            2017     340
            2018    2488
dtype: int64

In [55]:
labels.groupby('country').size()

country
Tajikistan     189
Uzbekistan    8246
dtype: int64

In [46]:
labels.groupby('year').size()

year
2008      26
2011     213
2015    1299
2016    4069
2017     340
2018    2488
dtype: int64